<?php
session_start();
require_once __DIR__ . '/../database/db_connect.php';

if (!isset($_SESSION['emp_no']) || !($_SESSION['is_manager'] ?? false)) {
    header("Location: ../index.php");
    exit;
}

$manager_emp_no = $_SESSION['emp_no'];

$stmt = $pdo->prepare("SELECT first_name, last_name FROM employees WHERE emp_no = ?");
$stmt->execute([$manager_emp_no]);
$manager = $stmt->fetch();

$reviews = $pdo->query("
    SELECT pr.*, 
           e.first_name, e.last_name, e.emp_no,
           r.first_name as reviewer_first, r.last_name as reviewer_last,
           d.dept_name, t.title
    FROM performance_reviews pr
    JOIN employees e ON pr.emp_no = e.emp_no
    JOIN employees r ON pr.reviewer_emp_no = r.emp_no
    LEFT JOIN dept_emp de ON e.emp_no = de.emp_no 
        AND (de.to_date IS NULL OR de.to_date > CURRENT_DATE)
    LEFT JOIN departments d ON de.dept_no = d.dept_no
    LEFT JOIN titles t ON e.emp_no = t.emp_no 
        AND (t.to_date IS NULL OR t.to_date > CURRENT_DATE)
    ORDER BY pr.review_date DESC, pr.created_at DESC
    LIMIT 100
")->fetchAll(PDO::FETCH_ASSOC);

// Export as CSV 
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="Performance_Reviews_' . date('Y-m-d') . '.csv"');

// UTF-8 BOM for Excel
echo "\xEF\xBB\xBF";

echo "PERFORMANCE REVIEWS REPORT\n";
echo "Generated: " . date('F d, Y g:i A') . "\n";
echo "Generated by: " . $manager['first_name'] . ' ' . $manager['last_name'] . "\n";
echo "Total Reviews: " . count($reviews) . "\n";
echo "\n";

// summary Statistics
echo "SUMMARY STATISTICS\n";
echo "Rating,Count,Percentage\n";

$rating_counts = array();
foreach ($reviews as $review) {
    $rating = $review['rating'];
    if (!isset($rating_counts[$rating])) $rating_counts[$rating] = 0;
    $rating_counts[$rating]++;
}

$total = count($reviews);
for ($i = 5; $i >= 1; $i--) {
    $count = $rating_counts[$i] ?? 0;
    $pct = ($total > 0) ? ($count / $total * 100) : 0;
    echo $i . ' Stars,' . $count . ',' . number_format($pct, 1) . "%\n";
}
echo "\n";

// detailed Reviews
echo "DETAILED REVIEWS\n";
echo "Employee,Emp #,Department,Title,Review Date,Rating,Reviewer,Performance Summary,Key Strengths,Areas for Improvement,Goals & Objectives,Additional Comments\n";

foreach ($reviews as $review) {
    // goes through structured comments
    $comments = $review['comments'] ?? '';
    $summary = '';
    $strengths = '';
    $improvements = '';
    $additional = '';
    
    if (preg_match('/PERFORMANCE SUMMARY:\s*(.+?)(?=\n\nKEY STRENGTHS:|$)/s', $comments, $match)) {
        $summary = trim($match[1]);
    }
    if (preg_match('/KEY STRENGTHS:\s*(.+?)(?=\n\nAREAS FOR IMPROVEMENT:|$)/s', $comments, $match)) {
        $strengths = trim($match[1]);
    }
    if (preg_match('/AREAS FOR IMPROVEMENT:\s*(.+?)(?=\n\nADDITIONAL COMMENTS:|$)/s', $comments, $match)) {
        $improvements = trim($match[1]);
    }
    if (preg_match('/ADDITIONAL COMMENTS:\s*(.+?)$/s', $comments, $match)) {
        $additional = trim($match[1]);
    }
    
    // if not structured, put all in summary
    if (empty($summary) && !empty($comments)) {
        $summary = $comments;
    }
    
    //output row
    echo '"' . $review['first_name'] . ' ' . $review['last_name'] . '",';
    echo $review['emp_no'] . ',';
    echo '"' . ($review['dept_name'] ?? 'N/A') . '",';
    echo '"' . ($review['title'] ?? 'N/A') . '",';
    echo '"' . $review['review_date'] . '",';
    echo $review['rating'] . ',';
    echo '"' . $review['reviewer_first'] . ' ' . $review['reviewer_last'] . '",';
    echo '"' . str_replace('"', '""', $summary) . '",';
    echo '"' . str_replace('"', '""', $strengths) . '",';
    echo '"' . str_replace('"', '""', $improvements) . '",';
    echo '"' . str_replace('"', '""', $review['goals'] ?? '') . '",';
    echo '"' . str_replace('"', '""', $additional) . '"';
    echo "\n";
}

echo "\n";
echo "REPORT NOTES\n";
echo "This report contains confidential performance information\n";
echo "Generated on: " . date('F d, Y') . "\n";
?>