<?php
session_start();
require_once __DIR__ . '/../database/db_connect.php';

if (!isset($_SESSION['emp_no']) || !($_SESSION['is_manager'] ?? false)) {
    header("Location: ../index.php");
    exit;
}

$manager_emp_no = $_SESSION['emp_no'];

// gets manager details
$stmt = $pdo->prepare("SELECT first_name, last_name FROM employees WHERE emp_no = ?");
$stmt->execute([$manager_emp_no]);
$manager = $stmt->fetch();

// gets data
$total_employees = $pdo->query("SELECT COUNT(*) FROM employees")->fetchColumn();
$total_departments = $pdo->query("SELECT COUNT(*) FROM departments")->fetchColumn();

$dept_distribution = $pdo->query("
    SELECT d.dept_name, COUNT(de.emp_no) as count
    FROM departments d
    LEFT JOIN dept_emp de ON d.dept_no = de.dept_no 
        AND (de.to_date IS NULL OR de.to_date > CURRENT_DATE)
    GROUP BY d.dept_name
    ORDER BY count DESC
")->fetchAll(PDO::FETCH_ASSOC);

$salary_ranges = $pdo->query("
    SELECT 
        CASE 
            WHEN salary < 50000 THEN 'Under $50k'
            WHEN salary >= 50000 AND salary < 75000 THEN '$50k - $75k'
            WHEN salary >= 75000 AND salary < 100000 THEN '$75k - $100k'
            WHEN salary >= 100000 AND salary < 150000 THEN '$100k - $150k'
            ELSE 'Over $150k'
        END as salary_range,
        COUNT(*) as count
    FROM salaries
    WHERE to_date IS NULL OR to_date > CURRENT_DATE
    GROUP BY salary_range
    ORDER BY MIN(salary)
")->fetchAll(PDO::FETCH_ASSOC);

$avg_tenure = $pdo->query("SELECT AVG(DATEDIFF(CURRENT_DATE, hire_date) / 365.25) as avg_years FROM employees")->fetchColumn();
$avg_salary = $pdo->query("SELECT AVG(salary) FROM salaries WHERE to_date IS NULL OR to_date > CURRENT_DATE")->fetchColumn();

// Export as CSV 
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="Analytics_Report_' . date('Y-m-d') . '.csv"');

// UTF-8 BOM for Excel
echo "\xEF\xBB\xBF";

echo "ANALYTICS REPORT\n";
echo "Generated: " . date('F d, Y g:i A') . "\n";
echo "Generated by: " . $manager['first_name'] . ' ' . $manager['last_name'] . "\n";
echo "\n";

// quick Statistics
echo "QUICK STATISTICS\n";
echo "Metric,Value\n";
echo "Total Employees," . number_format($total_employees) . "\n";
echo "Total Departments," . number_format($total_departments) . "\n";
echo "Average Tenure," . number_format($avg_tenure, 1) . " years\n";
echo "Average Salary,$" . number_format($avg_salary, 2) . "\n";
echo "\n";

// department distribution
echo "DEPARTMENT DISTRIBUTION\n";
echo "Department,Employees\n";
foreach ($dept_distribution as $dept) {
    echo '"' . $dept['dept_name'] . '",' . $dept['count'] . "\n";
}
echo "\n";

// salary Distribution
echo "SALARY DISTRIBUTION\n";
echo "Salary Range,Employees,Percentage\n";
$total_sal = array_sum(array_column($salary_ranges, 'count'));
foreach ($salary_ranges as $sal) {
    $pct = ($total_sal > 0) ? ($sal['count'] / $total_sal * 100) : 0;
    echo '"' . $sal['salary_range'] . '",' . $sal['count'] . ',' . number_format($pct, 1) . "%\n";
}
echo "\n";


echo "REPORT NOTES\n";
echo "This report contains confidential information\n";
echo "Generated on: " . date('F d, Y') . "\n";
?>